version: 2
jobs:
 build:
   working_directory: /home/circleci/circleci-docker-openjdk-node
   docker:
     - image: circleci/node:6.11
   environment:
     - DOCKER_REPO: teviotia
     - DOCKER_ARTIFACT: circleci-docker-openjdk-node
   steps:
     - checkout
     - setup_remote_docker
     - run: |
         git config --global user.email "circleci@example.com"
         git config --global user.name "Circle CI"
     - run: sudo npm install --global semver@5.3.0
     - run: docker build -t "circleci-docker-openjdk-node:latest" .
     - deploy:
         command: ./bash_libs/tag-version.sh > ~/.build_version
     - deploy:
         command: ./bash_libs/deploy-to-repo.sh "circleci-docker-openjdk-node:latest" "$(cat ~/.build_version)"
