version: 2
jobs:
 build:
   working_directory: /home/circleci/circleci-docker-openjdk-node
   docker:
     - image: circleci/node:6.11
   environment:
     - DOCKER_REPO: teviotia
     - DOCKER_ARTIFACT: circleci-docker-openjdk-node
   steps:
     - checkout
     - setup_remote_docker
     - restore_cache:
         keys:
           - docker_v1-openjdk:8u131
           - docker_v1
     - run: ./bash_libs/cache-docker.sh openjdk:8u131
     - save_cache:
         key: docker_v1-openjdk:8u131
         paths:
           - /home/circleci/.dockercache
     - run: |
         git config --global user.email "circleci@example.com"
         git config --global user.name "Circle CI"
     - run: sudo npm install --global semver@5.3.0
     - run: docker build -t "${DOCKER_ARTIFACT}:latest" .
     - deploy:
         command: ./bash_libs/tag-version.sh > ~/.build_version
     - deploy:
         command: ./bash_libs/deploy-to-repo.sh "${DOCKER_ARTIFACT}:latest" "$(cat ~/.build_version)"
